version: '3'
services:
  wordpress:
    depends_on:
      - db
    image: wordpress:4.8
    restart: always
    volumes:
      - ./ww1:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: p@ssw0rd123
    ports:
      - 8081:80 # Expose http and https
      - 8443:443
    networks:
      - backend
  db:
    image: mysql:5.7
    restart: always
    volumes:
       - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd123
    networks:
      - backend
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: p4ssw0rd123
    networks:
      - backend
networks:
  back:
volumes:
  db_data:
